plugins: ontology-importer added
obdasystems/eddy pull request #200
Opened 2022-05-30 11:25 UTC by MariaRosariaFraraccio

2022-06-01 14:52 UTC, mnamici requested changes
Ok un paio di osservazioni dopo una prima occhiata:
1) il file db.db non dovrebbe essere parte della PR
2) sarebbe opportuno integrare l'sql all'interno del plugin, non in un file separato. I plugin builtin devono poter eseguire da un formato zip, quindi avere accesso a risorse che non siano in forma di bytecode python è più articolato. Integrarli come stringhe sarebbe già sufficiente.
3) mi sembra che il database venga creato nella cwd del processo, il che è piuttosto fastidioso, sarebbe opportuno crearlo nella cartella dati apposita per-piattaforma (vedi la macro `@data` in expandpath)
4) per la modifica alla sessione vediamo se c'è un segnale che possiamo usare, in caso alternativo lo creiamo (e.g. sgnProjectSaved).

(edit: il sgnProjectSaved c'è già in effetti, c'è qualche ragione per cui non funziona usando quello? Forse non viene emesso?)

2022-06-08 18:04 UTC, mnamici commented
Ho riordinato le modifiche. 

Da un primo test veloce ho notato che se si esegue la seguente sequenza di azioni:
1) seleziona il pulsante di importazione
2) seleziona il nome del diagramma
3) inserisci un numero per lo spaziamento, poi cancella fino a che il campo è vuoto

si ottiene la seguente eccezione:
```
Traceback (most recent call last):
  File "/home/manuel/Workspace/eddy/eddy/plugins/ontology-importer/ontology_importer.py", line 5665, in onSpaceFieldChanged
    space = int(space.strip())
ValueError: invalid literal for int() with base 10: ''
```

2022-06-08 18:10 UTC, mnamici commented
Il problema del segnale di salvataggio rimane, ma per il momento lasciamolo così.

Ad esempio che succede se l'applicazione crasha? Immagino l'importazione non rispecchia più lo stato del progetto.

2022-06-09 10:46 UTC, MariaRosariaFraraccio commented
Il problema dello SpaceForm dovrebbe essere risolto.

Per quanto riguarda il segnale al momento sì, è così, quindi bisogna sicuramente trovare un'altra soluzione

2022-06-09 19:47 UTC, mnamici commented
Ok il form è risolto ora comunque ci sono ancora un sacco di "rough edges" per considerarlo stabile, per esempio se cancello l'importazione questa viene fatta lo stesso, oppure se importo due volte la stessa ontologia l'importazione non viene effettuata ma viene lanciata un'eccezione per la violazione del vincolo UNIQUE (tenti comunque di fare l'inserimento).

Credi ci voglia molto per risolvere questi due bug in particolare? Sennò intanto rilasciamo così.

P.S. ho riorganizzato gli import e messo l'accesso alle classi Qt tramite il loro modulo per essere consistente col resto del progetto.
P.S. 2: ho fatto force push per mantenere le modifiche ordinate e rendere la revisione più facile, per continuare da qui non fare merge ma reset:
```bash
$ git fetch origin
$ git reset --hard origin/ontology-importer
```
dovresti vedere due commit a partire dal tuo branch ql-restriction.

2022-06-13 18:30 UTC, mnamici commented
Ok sono risolti ora, possiamo integrare.

2022-06-13 18:44 UTC, merged