Increase minimum distance between class nodes
obdasystems/eddy pull request #225
Opened 2022-08-11 10:16 UTC by MariaRosariaFraraccio

2022-08-13 12:25 UTC, mnamici requested changes

2022-08-13 12:25 UTC, mnamici commented on eddy/plugins/ontology-importer/ontology_importer.py
> +        self.space = 250
Questo mi sa mi era sfuggito quando ho fattorizzato min/max come costanti, in tal caso usiamo la costante altrimenti con tutti queste ripetizioni tra un pò iniziamo a fare confusione.

2022-08-13 16:01 UTC, MariaRosariaFraraccio commented on eddy/plugins/ontology-importer/ontology_importer.py
> +        self.space = DiagramPropertiesForm.MinSpace
Intendevi così?

2022-08-13 16:04 UTC, MariaRosariaFraraccio commented
`self.space = DiagramPropertiesForm.MinSpace`

Intendevi così?

2022-08-14 12:46 UTC, mnamici approved these changes
Sì esatto.

2022-08-14 17:11 UTC, merged